### ISSUE TITLE
Can't publish the application

### ISSUE THREAD

**Issue by Definitelyeson** [t0int1337/BunifuUiCrack#4]
Help me, i cant publish the app

**Comment by dualznz** [comment]
could you please provide some context, building both debug and release works just fine

**Comment by Definitelyeson** [comment]
I get this error
![image](https://github.com/user-attachments/assets/6d6d322e-1cdf-4f0d-b617-216594e68554)

`PLATFORM VERSION INFO
	Windows 			: 10.0.26100.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.9181.0 built by: NET481REL1LAST_C
	clr.dll 			: 4.8.9266.0 built by: NET481REL1LAST_B
	dfdll.dll 			: 4.8.9181.0 built by: NET481REL1LAST_C
	dfshim.dll 			: 10.0.26100.1150 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/Administrator/Desktop/pUB/NEW/Bunifu.application
	Application url			: file:///C:/Users/Administrator/Desktop/pUB/NEW/Application%20Files/Bunifu_1_0_0_0/Bunifu.exe.manifest

IDENTITIES
	Deployment Identity		: Bunifu.application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=fafcd585e41967de, processorArchitecture=msil
	Application Identity		: Bunifu.exe, Version=1.0.0.0, Culture=neutral, PublicKeyToken=fafcd585e41967de, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\Administrator\Desktop\pUB\NEW\Bunifu.application resulted in exception. Following failure messages were detected:
		+ Strong name signature not valid for this assembly Bunifu.Licensing.dll.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [10/23/2024 1:24:48 PM] : Activation of C:\Users\Administrator\Desktop\pUB\NEW\Bunifu.application has started.
	* [10/23/2024 1:24:48 PM] : Processing of deployment manifest has successfully completed.
	* [10/23/2024 1:24:48 PM] : Installation of the application has started.
	* [10/23/2024 1:24:48 PM] : Processing of application manifest has successfully completed.
	* [10/23/2024 1:24:51 PM] : Found compatible runtime version 4.0.30319.
	* [10/23/2024 1:24:51 PM] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [10/23/2024 1:24:55 PM] System.Deployment.Application.InvalidDeploymentException (SignatureValidation)
		- Strong name signature not valid for this assembly Bunifu.Licensing.dll.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyStrongNameAssembly(String filePath, AssemblyManifest assemblyManifest)
			at System.Deployment.Application.ComponentVerifier.VerifyComponents()
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

`

**Comment by dualznz** [comment]
did you override all the the Bunifu.Licensing.dll in all the folders within your \packages\Bunifu.Licensing.6.0.4\lib\ directory?
![image](https://github.com/user-attachments/assets/61de8939-3b2a-454a-b2a8-33476dd67682)

**Comment by Definitelyeson** [comment]
yes i already override all licensing, im using 4.8 but i dont think that its the problem. Did you published the application successfully?

**Comment by dualznz** [comment]
i build my applications via the Release state, since i wrote my own installer / updater and done use OnceClickInstall at all

**Comment by dualznz** [comment]
i can confirm that it is working as intended 
![image](https://github.com/user-attachments/assets/99fbe9ab-acf4-42ff-909e-9b75dc83f68f)

**Comment by Definitelyeson** [comment]
I always getting the same error
![{26CEF71E-CD86-4263-A540-184B0EEF6BBE}](https://github.com/user-attachments/assets/48e14e1d-971a-4ba8-9c28-8c4544b87383)
even thou i created a new application.
can you send me a sample for reference?

**Comment by dualznz** [comment]
ok i am also getting strong name error on publish but again i dont use publish i build the application in release mode instead of debug then i use my own installer to create the install package.

the publish is used in OneClick and the hashing is not accepted under the license which would make sense since the hashkey will be different than the offical.

when you download the package from nuget the application identifier that comes with it changes based off the cracked dll and thus they do not match.

i recommend not to use publish and use something like Advanced Installer or InstallShield or you just make your own.

**Comment by t0int1337** [comment]
Its because the DLL is edited, and not signed. `Strong name signature not valid for this assembly Bunifu.Licensing.dll.`
If you can, disable this enforcement.

**Comment by Definitelyeson** [comment]
do you know how to do it?

**Comment by imfryad** [comment]
let me know if you guys fixed this, cause i was about to use the framework, but now i am scared lol...
